### ISSUE TITLE
ValueError: 'Ref' is not in list

### ISSUE THREAD

**Issue by sirus20x6** [twlostow/assygen#1]
even after fixing the file naming issues and the mix of tabs and spaces I can't get it to process the position file.

Traceback (most recent call last):
  File "./assygen.py", line 294, in <module>
    producePrintoutsForLayer(sys.argv[1], "Top", canv)
  File "./assygen.py", line 268, in producePrintoutsForLayer
    pf = PickAndPlaceFileKicad('/home/sirus/G3_future/outputs/G3_future.CSV')
  File "./assygen.py", line 147, in __init__
    i_dsg = rows[0].index('Ref')
ValueError: 'Ref' is not in list

**Comment by KajWiik** [comment]
I can confirm this in KiCad 4.0.7. Tried with two CSV generators, same error.
